import { useCallback, useEffect, useState } from 'react'
import { adminApi } from '../../api/CompetitionClient'
import type { Competition, LeaderboardRow, News, Stock, Team, TeamCreated } from '../../types/Competition'
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n)
export default function AdminDashboard(){
 const [key,setKey]=useState(localStorage.getItem('adminKey')??'change-me-now');const [competitions,setCompetitions]=useState<Competition[]>([]);const [selected,setSelected]=useState<Competition|null>(null);const [stocks,setStocks]=useState<Stock[]>([]);const [teams,setTeams]=useState<Team[]>([]);const [news,setNews]=useState<News[]>([]);const [leaderboard,setLeaderboard]=useState<LeaderboardRow[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [codes,setCodes]=useState<TeamCreated[]>([])
 const run=async(job:()=>Promise<unknown>,success:string)=>{setBusy(true);setMessage('');try{await job();setMessage(success)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 const refresh=useCallback(async(id?:number)=>{localStorage.setItem('adminKey',key);const all=await adminApi.list(key);setCompetitions(all);const target=id??selected?.id??all[0]?.id;if(target){const [c,s,t,n,l]=await Promise.all([adminApi.get(key,target),adminApi.stocks(key,target),adminApi.teams(key,target),adminApi.news(key,target),adminApi.leaderboard(key,target)]);setSelected(c);setStocks(s);setTeams(t);setNews(n);setLeaderboard(l)}},[key,selected?.id])
 useEffect(()=>{refresh().catch(e=>setMessage(e.message))},[]) // eslint-disable-line react-hooks/exhaustive-deps
 const createCompetition=(form:FormData)=>run(async()=>{const c=await adminApi.create(key,{name:form.get('name'),durationSeconds:Number(form.get('duration')),defaultStartingBudget:Number(form.get('budget')),tickIntervalMs:1000});await refresh(c.id)},'Competition created')
 const createTeams=(form:FormData)=>run(async()=>{if(!selected)return;const count=Number(form.get('count'));const prefix=String(form.get('prefix'));const result=await adminApi.createTeams(key,selected.id,Array.from({length:count},(_,i)=>`${prefix} ${i+1}`),Number(form.get('budget')));setCodes(result);await refresh(selected.id)},'Teams created — copy the access codes now')
 const addNews=(form:FormData)=>run(async()=>{if(!selected)return;await adminApi.createNews(key,selected.id,{headline:form.get('headline'),description:form.get('description'),releaseSecond:Number(form.get('releaseSecond')),impactDurationSeconds:Number(form.get('duration')),impactStyle:form.get('style'),impacts:[{ticker:String(form.get('ticker')).toUpperCase(),impactPercent:Number(form.get('impact'))}]});await refresh(selected.id)},'News scheduled')
 const action=(name:string)=>selected&&run(async()=>{await adminApi.action(key,selected.id,name);await refresh(selected.id)},`${name.toUpperCase()} complete`)
 return <main className="app-shell"><header className="topbar"><div><span className="eyebrow">CONTROL ROOM</span><h1>Market Competition</h1></div><a href="/team/login" className="ghost">Team login →</a></header><section className="key-row"><label>Admin key <input type="password" value={key} onChange={e=>setKey(e.target.value)}/></label><button onClick={()=>refresh().catch(e=>setMessage(e.message))}>Connect</button></section>{message&&<div className="notice">{message}</div>}
 <div className="admin-grid"><section className="panel"><h2>1. Competition</h2><form action={createCompetition} className="stack"><input name="name" placeholder="Demo Trading Challenge" required/><div className="split"><input aria-label="Duration seconds" name="duration" type="number" defaultValue="3600"/><input aria-label="Budget" name="budget" type="number" defaultValue="1000000"/></div><button disabled={busy}>Create</button></form><select value={selected?.id??''} onChange={e=>refresh(Number(e.target.value))}>{competitions.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{selected&&<div className="status-card"><b>{selected.status}</b><span>{selected.elapsedSeconds}s / {selected.durationSeconds}s</span><span>{selected.stockCount} stocks · {selected.teamCount} teams</span>{selected.lockHash&&<code title={selected.lockHash}>{selected.lockHash.slice(0,16)}…</code>}</div>}</section>
 <section className="panel"><h2>2. Stock universe</h2><p>{stocks.length} configured stocks</p><div className="button-row"><button disabled={!selected||busy} onClick={()=>selected&&run(async()=>{await adminApi.defaults(key,selected.id);await refresh(selected.id)},'100-stock universe loaded')}>Load 100 defaults</button><button className="secondary" disabled={!selected||busy} onClick={()=>selected&&run(async()=>{const r=await adminApi.fetchPrices(key,selected.id);await refresh(selected.id);setMessage(`Updated ${r.updated}; preserved ${r.preserved}`)},'Prices refreshed')}>Fetch latest</button></div><div className="mini-list">{stocks.slice(0,6).map(s=><span key={s.ticker}>{s.ticker} <b>{money(s.startingPrice)}</b></span>)}</div></section>
 <section className="panel"><h2>3. Teams</h2><form action={createTeams} className="stack"><div className="split"><input name="prefix" defaultValue="Team"/><input aria-label="Team count" name="count" type="number" min="1" defaultValue="10"/></div><input aria-label="Team budget" name="budget" type="number" defaultValue={selected?.defaultStartingBudget??1000000}/><button disabled={!selected||busy}>Create teams</button></form><p>{teams.length} teams configured</p>{codes.length>0&&<div className="codes">{codes.map(c=><code key={c.id}>{c.name}: {c.accessCode}</code>)}</div>}</section>
 <section className="panel"><h2>4. Reference market</h2><p>Generate and persist the full seeded path before lock.</p><button disabled={!selected||busy} onClick={()=>selected&&run(async()=>{const r=await adminApi.generate(key,selected.id);await refresh(selected.id);setMessage(`${r.points.toLocaleString()} reference points generated`)},'Reference generated')}>Generate path</button></section>
 <section className="panel wide"><h2>5. News scheduler</h2><form action={addNews} className="news-form"><input name="headline" placeholder="Breaking headline" required/><input name="description" placeholder="Public description" required/><input name="releaseSecond" type="number" placeholder="Release second" required/><input name="ticker" placeholder="Ticker" required/><input name="impact" type="number" step=".1" placeholder="Impact %" required/><input name="duration" type="number" defaultValue="60"/><select name="style"><option>RAMP</option><option>INSTANT</option></select><button disabled={!selected||busy}>Schedule</button></form><div className="mini-list">{news.map(n=><span key={n.id}>{n.releaseSecond}s · {n.headline}</span>)}</div></section>
 <section className="panel wide"><h2>6. Run competition</h2><div className="button-row controls"><button onClick={()=>action('lock')}>Lock</button><button onClick={()=>action('start')}>Start</button><button onClick={()=>action('pause')} className="secondary">Pause</button><button onClick={()=>action('resume')} className="secondary">Resume</button><button onClick={()=>action('end')} className="danger">End</button></div></section><section className="panel wide"><h2>Live leaderboard</h2><Leaderboard rows={leaderboard}/></section></div></main>
}
export function Leaderboard({rows}:{rows:LeaderboardRow[]}){return <div className="table-wrap"><table><thead><tr><th>#</th><th>Team</th><th>Value</th><th>P&amp;L</th><th>Return</th></tr></thead><tbody>{rows.map(r=><tr key={r.teamId}><td>{r.rank}</td><td>{r.teamName}</td><td>{money(r.totalPortfolioValue)}</td><td className={r.profitLoss>=0?'up':'down'}>{money(r.profitLoss)}</td><td>{r.returnPercent.toFixed(2)}%</td></tr>)}</tbody></table></div>}
