import { useCallback,useEffect,useMemo,useState } from 'react';import { useNavigate,useParams } from 'react-router-dom';import { teamApi } from '../../api/CompetitionClient';import type { Market,Portfolio,PricePoint,Stock } from '../../types/Competition';import StockPriceChart from '../shared/StockPriceChart';import { Leaderboard } from './AdminDashboard'
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n);const clock=(s:number)=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`
export default function CompetitionDashboard(){
 const{id}=useParams();const competitionId=Number(id);const navigate=useNavigate();const session=useMemo(()=>{try{return JSON.parse(localStorage.getItem('teamSession')??'null')}catch{return null}},[]);const[market,setMarket]=useState<Market|null>(null);const[portfolio,setPortfolio]=useState<Portfolio|null>(null);const[selected,setSelected]=useState<Stock|null>(null);const[history,setHistory]=useState<PricePoint[]>([]);const[quantity,setQuantity]=useState(1);const[error,setError]=useState('');const[query,setQuery]=useState('')
 const refresh=useCallback(async()=>{if(!session?.token){navigate('/team/login');return}const[m,p]=await Promise.all([teamApi.market(competitionId,session.token),teamApi.portfolio(competitionId,session.token)]);setMarket(m);setPortfolio(p);setSelected(old=>old?m.stocks.find((s:Stock)=>s.ticker===old.ticker)??m.stocks[0]:m.stocks[0])},[competitionId,navigate,session?.token])
 useEffect(()=>{refresh().catch(e=>setError(e.message));if(!session?.token)return;const events=new EventSource(teamApi.eventUrl(competitionId,session.token));events.addEventListener('tick',()=>refresh().catch(()=>{}));events.addEventListener('news',()=>refresh().catch(()=>{}));events.addEventListener('leaderboard',()=>refresh().catch(()=>{}));return()=>events.close()},[refresh,competitionId,session?.token])
 useEffect(()=>{if(selected&&session?.token)teamApi.history(competitionId,selected.ticker,session.token).then(setHistory).catch(e=>setError(e.message))},[selected?.ticker,market?.competition.elapsedSeconds]) // eslint-disable-line react-hooks/exhaustive-deps
 const trade=async(side:'buy'|'sell')=>{if(!selected)return;setError('');try{await teamApi.order(competitionId,side,selected.ticker,quantity,session.token);await refresh()}catch(e){setError((e as Error).message)}};const stocks=market?.stocks.filter(s=>`${s.ticker} ${s.companyName}`.toLowerCase().includes(query.toLowerCase()))??[]
 if(!market||!portfolio)return <main className="loading">Connecting to the market… {error}</main>
 return <main className="trading-shell"><header className="market-header"><div><span className="eyebrow">{market.competition.name}</span><h1>{session.teamName}</h1></div><div className={`market-state ${market.competition.status.toLowerCase()}`}><b>{market.competition.status}</b><span>{clock(market.competition.remainingSeconds)}</span></div><div className="account"><span>Portfolio value</span><b>{money(portfolio.totalPortfolioValue)}</b><em className={portfolio.totalPnL>=0?'up':'down'}>{portfolio.returnPercent.toFixed(2)}%</em></div></header>{error&&<div className="error banner">{error}</div>}
 <div className="trading-grid"><aside className="watchlist"><input placeholder="Search 100 stocks" value={query} onChange={e=>setQuery(e.target.value)}/>{stocks.map(s=><button key={s.ticker} onClick={()=>setSelected(s)} className={selected?.ticker===s.ticker?'active':''}><span><b>{s.ticker}</b><small>{s.companyName}</small></span><span><b>{money(s.livePrice)}</b><small className={s.changePercent>=0?'up':'down'}>{s.changePercent.toFixed(2)}%</small></span></button>)}</aside>
 <section className="market-main">{selected&&<><div className="quote-head"><div><span>{selected.sector}</span><h2>{selected.ticker}</h2><p>{selected.companyName}</p></div><div><strong>{money(selected.livePrice)}</strong><em className={selected.changePercent>=0?'up':'down'}>{selected.changePercent.toFixed(2)}%</em></div></div><StockPriceChart points={history} ticker={selected.ticker}/><div className="trade-ticket"><input aria-label="Quantity" type="number" min="1" step="1" value={quantity} onChange={e=>setQuantity(Math.max(1,Math.floor(Number(e.target.value))))}/><button disabled={market.competition.status!=='RUNNING'} onClick={()=>trade('buy')}>Buy</button><button disabled={market.competition.status!=='RUNNING'} className="sell" onClick={()=>trade('sell')}>Sell</button><span>Est. {money(selected.livePrice*quantity)}</span></div></>}</section>
 <aside className="right-rail"><section className="panel"><h3>Portfolio</h3><div className="metric"><span>Cash</span><b>{money(portfolio.cashBalance)}</b></div><div className="metric"><span>Holdings</span><b>{money(portfolio.holdingsMarketValue)}</b></div>{portfolio.holdings.map(h=><div className="holding" key={h.ticker}><b>{h.ticker}</b><span>{h.quantity} × {money(h.livePrice)}</span><em className={h.unrealizedPnL>=0?'up':'down'}>{money(h.unrealizedPnL)}</em></div>)}</section><section className="panel"><h3>Live news</h3>{market.news.length?market.news.slice().reverse().map(n=><article className="news-item" key={n.id}><time>{clock(n.releaseSecond)}</time><b>{n.headline}</b><p>{n.description}</p></article>):<p className="muted">No news released yet.</p>}</section></aside><section className="leaderboard-strip"><h3>Leaderboard</h3><Leaderboard rows={market.leaderboard}/></section></div></main>
}
